### ISSUE TITLE
What is MAX_NB?

### ISSUE THREAD

**Issue by Oktai15** [wengong-jin/icml18-jtnn#11]
What does ```MAX_NB``` stand for in your code? Maybe it is batch_size, but there are different values for it in each file

**Comment by wengong-jin** [comment]
Hi,

It is the maximum degree of the molecular graph.

**Comment by Oktai15** [comment]
@wengong-jin but why did you put different values for this variable in different files?

**Comment by wengong-jin** [comment]
Well, in mpn.py, MAX_NB means the maximum degree of junction tree. That's why it is different from jtnn_enc.py
