### ISSUE TITLE
sample_prior in sample.py

### ISSUE THREAD

**Issue by Oktai15** [wengong-jin/icml18-jtnn#13]
`sample_prior` should get `prob_decode=True`, isn't it?

https://github.com/wengong-jin/icml18-jtnn/blob/master/molvae/sample.py

**Comment by wengong-jin** [comment]
Yes, I made a mistake when cleaning up and releasing my code. Now it is fixed. I just checked, my original script has `prob_decode=True`. So the result in the paper is correct.

**Comment by Oktai15** [comment]
@wengong-jin I have a strange problem when I specify prob_decode=True.

`/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cuh:109: void renormRowsL1(T *, long, long) [with T = float]: block: [0,0,0], thread: [0,0,0] Assertion THCNumerics<T>::gt(sum, zero) failed.
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/generic/THCStorage.c line=36 error=59 : device-side assert triggered`

Traceback (most recent call last):
  sample.py, line 32, in <module>
    gen_smiles.append(model.sample_prior(prob_decode=True))
  jtnn_vae.py, line 190, in sample_prior
    mol = self.decode(tree_vec, mol_vec, prob_decode)
  jtnn_vae.py, line 198, in decode
    pred_root, pred_nodes = self.decoder.decode(tree_vec, prob_decode)
  jtnn_dec.py, line 227, in decode
    slots = self.vocab.get_slots(wid)
  datautils.py, line 25, in get_slots
    return copy.deepcopy(self.slots[idx])

`RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/generic/THCStorage.c:36`

Do you know what happened?

**Comment by Oktai15** [comment]
@wengong-jin Okay, I ran my program with CUDA_LAUNCH_BLOCKING=1 and found out that problem with the following:
`sort_wid = torch.multinomial(pred_score.data.squeeze(), 5)`

Do you know why?

I printed `pred_score.data.squeeze()`:
tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], device='cuda:0')

**Comment by Oktai15** [comment]
@wengong-jin I suppose the problem is cuda bug. I wrote issue:
https://github.com/pytorch/pytorch/issues/9062

**Comment by XiuHuan-Yap** [comment]
Hi @Oktai15 , I wonder if you found a solution to this problem, esp since the issue remains unaddressed in pytorch/pytorch#9062? 

I figured a workaround by using:
                   ` sort_wid = torch.multinomial(pred_score.data.squeeze(), 5, **replacement=True**)
                    **sort_wid = torch.unique(sort_wid**)`
Also needed to edit the for loop a few lines later:
        `for wid in sort_wid[:len(sort_wid)]:`

This allows sort_wid to return a torch.Tensor vector of size 5, which can then be trimmed down to the appropriate size using torch.unique. 

I also noticed this in jin's jtnn/jtnn_vae.py :
          `probs = nn.Softmax()(scores.view(1,-1)).squeeze() + 1e-5 #prevent prob = 0`
which maybe could also be applicable in this case? 

Happy to hear your thoughts.

**Comment by Oktai15** [comment]
@XiuHuan-Yap I didn't find solution. I will open new issue if I don't get any comment

**Comment by KekeZy** [comment]
Excuse me,have you solved this problem? @Oktai15

**Comment by Oktai15** [comment]
@KekeZy check issue above

**Comment by KekeZy** [comment]
thank you very much @Oktai15

**Comment by Colanim** [comment]
I had the same problem.

Turned out, my distribution was batched, and each sample of the batch had different amount of 0.
