### ISSUE TITLE
No file called model.4

### ISSUE THREAD

**Issue by NamanChuriwala** [wengong-jin/icml18-jtnn#18]
Dear Wengong:
You use the following code to run gen_latent.py in the bo folder.:
**python gen_latent.py --data ../data/train.txt --vocab ../data/vocab.txt \
--hidden 450 --depth 3 --latent 56 \
--model ../molvae/MPNVAE-h450-L56-d3-beta0.005/model.4**
But the system throws the following error:
**No such file or directory: '../molvae/MPNVAE-h450-L56-d3-beta0.005/model.4**
 as the file in molvae is named model.iter-4 instead of model.4

I tried passing model-iter.4 instead of model.4 but it still shows an error. Could you help resolve this?
Thanks.

**Comment by NamanChuriwala** [comment]
Hi, This is the error I'm still getting.

**/home/naman_churiwala_quantiphi_com/anaconda3/envs/ChemGAN_1/lib/python2.7/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "gen_latent.py", line 41, in <module>
    model.load_state_dict(torch.load(opts.model_path))
  File "/home/naman_churiwala_quantiphi_com/anaconda3/envs/ChemGAN_1/lib/python2.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/naman_churiwala_quantiphi_com/anaconda3/envs/ChemGAN_1/lib/python2.7/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
  File "/home/naman_churiwala_quantiphi_com/anaconda3/envs/ChemGAN_1/lib/python2.7/site-packages/torch/serialization.py", line 508, in persistent_load
    data_type(size), location)
  File "/home/naman_churiwala_quantiphi_com/anaconda3/envs/ChemGAN_1/lib/python2.7/site-packages/torch/serialization.py", line 104, in default_restore_location
    result = fn(storage, location)
  File "/home/naman_churiwala_quantiphi_com/anaconda3/envs/ChemGAN_1/lib/python2.7/site-packages/torch/serialization.py", line 75, in _cuda_deserialize
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.**

**Comment by NamanChuriwala** [comment]
Hi,

The input dimensions being provided by us are not compatible with that of the model in model.iter-4.
I tried passing hidden size as 200 seeing the errors, but the exact error is shown even then

**, line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for JTNNVAE:
        size mismatch for embedding.weight: copying a param of torch.Size([780, 200]) from checkpoint, where the shape is torch.Size([780, 450]) in current model.
        size mismatch for jtnn.embedding.weight: copying a param of torch.Size([780, 200]) from checkpoint, where the shape is torch.Size([780, 450]) in current model.
        size mismatch for jtnn.W_z.bias: copying a param of torch.Size([200]) from checkpoint, where the shape is torch.Size([450]) in current model.
        size mismatch for jtnn.W_z.weight: copying a param of torch.Size([200, 400]) from checkpoint, where the shape is torch.Size([450, 900]) in current model.
        size mismatch for jtnn.W_r.weight: copying a param of torch.Size([200, 200]) from checkpoint, where the shape is torch.Size([450, 450]) in current model.
        size mismatch for jtnn.U_r.bias: copying a param of torch.Size([200]) from checkpoint, where the shape is torch.Size([450]) in current model.
        size mismatch for jtnn.U_r.weight: copying a param of torch.Size([200, 200]) from checkpoint, where the shape is torch.Size([450, 450]) in current model.
        size mismatch for jtnn.W_h.bias: copying a param of torch.Size([200]) from checkpoint, where the shape is torch.Size([450]) in current model.
        size mismatch for jtnn.W_h.weight: copying a param of torch.Size([200, 400]) from checkpoint, where the shape is torch.Size([450, 900]) in current model.
        size mismatch for jtnn.W.bias: copying a param of torch.Size([200]) from checkpoint, where the shape is torch.Size([450]) in current model.
        size mismatch for jtnn.W.weight: copying a param of torch.Size([200, 400]) from checkpoint, where the shape is torch.Size([450, 900]) in current model.
        size mismatch for jtmpn.W_i.weight: copying a param of torch.Size([200, 40]) from checkpoint, where the shape is torch.Size([450, 40]) in current model.
        size mismatch for jtmpn.W_h.weight: copying a param of torch.Size([200, 200]) from checkpoint, where the shape is torch.Size([450, 450]) in current model.
        size mismatch for jtmpn.W_o.bias: copying a param of torch.Size([200]) from checkpoint, where the shape is torch.Size([450]) in current model.
        size mismatch for jtmpn.W_o.weight: copying a param of torch.Size([200, 235]) from checkpoint, where the shape is torch.Size([450, 485]) in current model.
        size mismatch for mpn.W_i.weight: copying a param of torch.Size([200, 50]) from checkpoint, where the shape is torch.Size([450, 50]) in current model.
        size mismatch for mpn.W_h.weight: copying a param of torch.Size([200, 200]) from checkpoint, where the shape is torch.Size([450, 450]) in current model.
        size mismatch for mpn.W_o.bias: copying a param of torch.Size([200]) from checkpoint, where the shape is torch.Size([450]) in current model.
        size mismatch for mpn.W_o.weight: copying a param of torch.Size([200, 239]) from checkpoint, where the shape is torch.Size([450, 489]) in current model.
        size mismatch for decoder.embedding.weight: copying a param of torch.Size([780, 200]) from checkpoint, where the shape is torch.Size([780, 450]) in current model.
        size mismatch for decoder.W_z.bias: copying a param of torch.Size([200]) from checkpoint, where the shape is torch.Size([450]) in current model.
        size mismatch for decoder.W_z.weight: copying a param of torch.Size([200, 400]) from checkpoint, where the shape is torch.Size([450, 900]) in current model.
        size mismatch for decoder.U_r.weight: copying a param of torch.Size([200, 200]) from checkpoint, where the shape is torch.Size([450, 450]) in current model.
        size mismatch for decoder.W_r.bias: copying a param of torch.Size([200]) from checkpoint, where the shape is torch.Size([450]) in current model.
        size mismatch for decoder.W_r.weight: copying a param of torch.Size([200, 200]) from checkpoint, where the shape is torch.Size([450, 450]) in current model.
        size mismatch for decoder.W_h.bias: copying a param of torch.Size([200]) from checkpoint, where the shape is torch.Size([450]) in current model.
        size mismatch for decoder.W_h.weight: copying a param of torch.Size([200, 400]) from checkpoint, where the shape is torch.Size([450, 900]) in current model.
        size mismatch for decoder.W.bias: copying a param of torch.Size([200]) from checkpoint, where the shape is torch.Size([450]) in current model.
        size mismatch for decoder.W.weight: copying a param of torch.Size([200, 228]) from checkpoint, where the shape is torch.Size([450, 478]) in current model.
        size mismatch for decoder.U.bias: copying a param of torch.Size([200]) from checkpoint, where the shape is torch.Size([450]) in current model.
        size mismatch for decoder.U.weight: copying a param of torch.Size([200, 428]) from checkpoint, where the shape is torch.Size([450, 928]) in current model.
        size mismatch for decoder.W_o.weight: copying a param of torch.Size([780, 200]) from checkpoint, where the shape is torch.Size([780, 450]) in current model.
        size mismatch for decoder.U_s.weight: copying a param of torch.Size([1, 200]) from checkpoint, where the shape is torch.Size([1, 450]) in current model.
        size mismatch for T_mean.weight: copying a param of torch.Size([28, 200]) from checkpoint, where the shape is torch.Size([28, 450]) in current model.
        size mismatch for T_var.weight: copying a param of torch.Size([28, 200]) from checkpoint, where the shape is torch.Size([28, 450]) in current model.
        size mismatch for G_mean.weight: copying a param of torch.Size([28, 200]) from checkpoint, where the shape is torch.Size([28, 450]) in current model.
        size mismatch for G_var.weight: copying a param of torch.Size([28, 200]) from checkpoint, where the shape is torch.Size([28, 450]) in current model.**

**Comment by NamanChuriwala** [comment]
Hi,
Solved the issue, model is running fine now. Although I'm not able to make use of cuda, model is running fine.

**Comment by techstone** [comment]
> Hi,
> Solved the issue, model is running fine now. Although I'm not able to make use of cuda, model is running fine.

I encounter the same "size mismatch" problem. Could you please tell me how do you fix it,  Thank you.
