### ISSUE TITLE
'module' object has no attribute 'MatrixInversePSD'

### ISSUE THREAD

**Issue by NamanChuriwala** [wengong-jin/icml18-jtnn#20]
While running the run_bo.py file in Bayesian Optimization, I get the following error:
**File "run_bo.py", line 87, in <module>
    sgp.train_via_ADAM(X_train, 0 * X_train, y_train, X_test, X_test * 0, y_test, minibatch_size = 10 * M, max_iterations = 100, learning_rate = 0.001)
  File "/home/naman_churiwala_quantiphi_com/icml18-jtnn/bo/sparse_gp.py", line 213, in train_via_ADAM
    e = self.getEnergy()
  File "/home/naman_churiwala_quantiphi_com/icml18-jtnn/bo/sparse_gp.py", line 102, in getEnergy
    self.sparse_gp.compute_output()
  File "/home/naman_churiwala_quantiphi_com/icml18-jtnn/bo/sparse_gp_theano_internal.py", line 77, in compute_output
    self.KzzInv = T.nlinalg.MatrixInversePSD()(self.Kzz)
AttributeError: 'module' object has no attribute 'MatrixInversePSD'**

Is it possible that the attribute is MatrixInverse instead of MatrixInversePSD?

I have run run_bo.py previously without encountering the above error, but this seems to be a problem now. Can you help me with this? Thanks

**Comment by anny0316** [comment]
@NamanChuriwala  Hello,  I also encountered this problem, but I only installed a version of theano, how do I solve it? thank you.

**Comment by To-phoenix-zhw** [comment]
> @NamanChuriwala Hello, I also encountered this problem, but I only installed a version of theano, how do I solve it? thank you.

Have you solved this problem? I have the same question as yours.
