### ISSUE TITLE
Is junction tree necessary?

### ISSUE THREAD

**Issue by jaechanglim** [wengong-jin/icml18-jtnn#3]
I think that molecular graph can be directly generated from latent vector of graph as junction tree is made from latent vector of junction tree. Have you ever tried it and it is worse than JTVAE?

**Comment by wengong-jin** [comment]
Hi,

Yes. I mentioned this possibility in my paper -- generating a graph node by node from its latent representation. In fact, this paper implemented this (https://arxiv.org/abs/1803.03324), though their model does not have a encoder (so pretty much like a language model). Their performed experiments on ZINC dataset, and showed show that 89.2% molecules are valid when sampled, while we get 100%. Unfortunately, they didn't report results on Bayesian optimization.

In molecule domain, previous work already tried to generate [SMILES](https://en.wikipedia.org/wiki/Simplified_molecular-input_line-entry_system) strings of molecules. If you look at how SMILES strings encode molecules, you will realize that generating SMILES is almost the same as generating a graph node by node.
