### ISSUE TITLE
clarification needed on the README in the fast_molvae folder

### ISSUE THREAD

**Issue by redBirdTx** [wengong-jin/icml18-jtnn#31]
Wengong, Thanks for the efforts in delivering a faster version of jtnn.

A quick question for the instructions to run the fast_molvae: For the training, you have two steps listed: 1. preprocess the data and 2. pretrain. I no longer see the vae_train.py called any more. Is the code intended to perform pretrain only? If so, where is the pretrain.py file in the fast_jtnn folder? I only find vae_train.py. There is a pretrain.py only in the older folders.

**Comment by wengong-jin** [comment]
Sorry for the typo. I changed the pretrain.py to vae_train.py. Please see the updated README
