### ISSUE TITLE
About a bug in   File "icml18-jtnn/fast_jtnn/chemutils.py", 

### ISSUE THREAD

**Issue by huangwb** [wengong-jin/icml18-jtnn#38]
I obain a bug when runing to icml18-jtnn/fast_jtnn/chemutils.py:
"
line 320, in <lambda>     
get_nid = lambda x:0 if node.is_leaf else node.nid 
NameError: name 'node' is not defined
"
I find that here the variable "node" should be "ctr_node".  The code is ok after I fixed it.

**Comment by wengong-jin** [comment]
Thanks for pointing this out. The correct fix is
```
get_nid = lambda x:0 if x.is_leaf else x.nid
```
The code has been fixed.
