### ISSUE TITLE
zero-dimensional tensor (at position 0) cannot be concatenated

### ISSUE THREAD

**Issue by leonhug** [wengong-jin/icml18-jtnn#6]
May you please help with this?
Anaconda/Python 2.7 and packages of newest version

> export PYTHONPATH=[PATH TO]icml18-jtnn/wengong-jin
> python pretrain.py --train ../data/train.txt --vocab ../data/vocab.txt --hidden 450 --depth 3 --latent 56 --batch 40 --save_dir pre_model/

Traceback (most recent call last):
  File "pretrain.py", line 69, in <module>
    loss, kl_div, wacc, tacc, sacc, dacc = model(batch, beta=0)
  File " python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File " icml18-jtnn/wengong-jin/jtnn/jtnn_vae.py", line 87, in forward
    assm_loss, assm_acc = self.assm(mol_batch, mol_vec, tree_mess)
  File " icml18-jtnn/wengong-jin/jtnn/jtnn_vae.py", line 132, in assm
    all_loss = torch.cat(all_loss).sum() / len(mol_batch)
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated

**Comment by wengong-jin** [comment]
Hi,
I apologize for my late reply. I think you are probably using pytorch v0.4. I run my code on pytorch v0.3, and it runs OK. If so, could you try modifying this line into
`all_loss = torch.stack(all_loss, dim=0).sum() / len(mol_batch)`

Thanks

**Comment by pyeguy** [comment]
setting `dim=0` didn't work for me in `pytorch v0.4` but switching to `pytorch v0.3` did
